// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace finalProject.Migrations
{
    [DbContext(typeof(animeContext))]
    [Migration("20220822043911_anime")]
    partial class anime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Personaje", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("altura")
                        .HasColumnType("TEXT");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("direccin")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("frase")
                        .HasColumnType("TEXT");

                    b.Property<float>("latitud")
                        .HasColumnType("REAL");

                    b.Property<float>("longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("poder")
                        .HasColumnType("TEXT");

                    b.Property<string>("pronunciacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("serieid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("serieid");

                    b.ToTable("personajes");
                });

            modelBuilder.Entity("Serie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("series");
                });

            modelBuilder.Entity("Personaje", b =>
                {
                    b.HasOne("Serie", "serie")
                        .WithMany("personaje")
                        .HasForeignKey("serieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serie");
                });

            modelBuilder.Entity("Serie", b =>
                {
                    b.Navigation("personaje");
                });
#pragma warning restore 612, 618
        }
    }
}
